name: Check VLESS Configurations

on:
  schedule:
    - cron: '0 */2 * * *' # Каждые 2 часа
  workflow_dispatch: # Позволяет запускать вручную

jobs:
  check-configs:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          pip install httpx
          # Установка Xray-core
          wget https://github.com/XTLS/Xray-core/releases/latest/download/xray-linux-64.zip
          unzip xray-linux-64.zip
          chmod +x xray

      - name: Run config checker
        run: python check_configs.py

      - name: Commit and push changes
        run: |
          git config --global user.name 'GitHub Action'
          git config --global user.email 'action@github.com'
          git add working_configs.json
          git commit -m "Update working configurations" || echo "No changes to commit"
          git push
        env:
          GITHUB_TOKEN: ${{ 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 }}
